export const FETCH_ORDERS = "FETCH_ORDERS"
export const GET_ORDER = "GET_ORDER"
export const TOGGLE_EDITING = "TOGGLE_EDITING"
export const CLEAR_EDITING_ORDER = "CLEAR_EDITING_ORDER"
export const HANDLE_INPUT_CHANGE = "HANDLE_INPUT_CHANGE"

export const ADD_TO_ORDERS = "ADD_TO_ORDERS"
export const SAVE_EDITED_ORDER = "SAVE_EDITED_ORDER"
export const DELETE_ORDER = "DELETE_ORDER"



//LOGIN ACTIONS
export const LOGIN_USER = "LOGIN_USER" 